#!/bin/bash

TOKEN=`echo -n '{"client":"myTestClient","pwd":"v8(9D1A>7n9J<","scope":[],"rw":false,"exp":4405688331,"hawkAlgorithm":"sha256"}' | \
	iron -i 1 -p $IRON_PASSWORD_1`

AUTHORIZATION=$(hawk -i $TOKEN -p 'v8(9D1A>7n9J<' -H localhost -P /protected -O 80 -M GET -a sha256 -m header)

STATUS=`curl -s -H "$AUTHORIZATION" http://localhost/protected -w "%{http_code}" -o /dev/null`;

if [ $STATUS -ne 401 ] ; then
	echo "... Expected 401 but got $STATUS";
	exit 1;
fi

