#!/bin/bash

AH=$(hawk -i `cat token` -p 'v8(9D1A>7n9J<' -H localhost -P /protected -O 80 -M DELETE -a sha256 -m header)

if [ `curl -s -X DELETE -H "$AH" http://localhost/protected -w "%{http_code}" -o /dev/null` -ne 403 ] ; then echo "Expected 401"; exit 1;  fi

