#!/bin/bash

AH=$(hawk -i `cat token` -p 'v8(9D1A>7n9J<' -H localhost -P /protectedxxx -O 80 -M GET -a sha256 -m header)

STATUS=`curl -s -H "$AH" http://localhost/protected -w "%{http_code}" -o /dev/null`;

if [ $STATUS -ne 402 ] ; then echo "Expected 401 but got $STATUS"; exit 1;  fi

